name: BananoEconomy
version: ${project.version}
main: banano.bananominecraft.bananoeconomy.BananoEconomyMain
api-version: 1.16
authors: [Kirby]
description: A Banano Tipbot for Minecraft
depend: [Vault]
commands:

  nodeinfo:
    description: Prints node info
    aliases: [node]

  deposit:
    aliases: [dep]
    description: Displays your deposit address

  tip:
    description: Send a tip to another player
    usage: |
      /<command> [amount] [player] [optional message] - sends provided amount to player

  withdraw:
    description: Withdraw bans to an address

  balance:
    description: Displays your balance
    aliases: [bal]

  history:
    description: Displays your transaction history
    usage: /<command> [last X transactions]
    aliases: [hist,transactions,trans]

  bc:
    aliases: [bananoeconomy,bananocraft,be]
    description: Generic admin command to provide plugin admin.
    permission: BananoEconomy.admin
    permission-message: You do not have /<permission>
    usage: |
      /<command> <setnode|freeze|unfreeze|explorer|serverwallet> <further parameters>

  showofflinetips:
    aliases: [showofflinepayments, showofflinetransactions]
    description: Displays the details of the changed transactions while the player was offline.

  representative:
    aliases: [rep]
    description: Manage your account's representative
    usage: /<command> <set <ban_address|random>|get>
    permission: BananoEconomy.representative
    permission-message: You do not have /<permission>

  receive:
    aliases: [rec]
    description: Manually receives any pending incoming transactions

permissions:
  BananoEconomy.nodeinfo.ip:
    description: This permission allows users to see the node IP with the nodeinfo command
    default: op
  BananoEconomy.admin:
    description: Access to the BananoCraft economy admin commands.
    default: op
  BananoEconomy.representative:
    description: Access to the /representative command.
    default: true


